name: CI
on:
  pull_request:
    branches: 
      - main
  push: 
    branches:
      - main     
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install deps
        run: yarn install
      - name: Patch multiformats # Needed because otherwise it does not build in Angular context
        run: patch node_modules/multiformats/types/src/cid.d.ts cid.patch
      - name: Build
        run: yarn run build -c production
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/bsky/browser # The folder the action should deploy.
        
